version: '3.8'


services:

  ##Microservices config
  user_service:
    build:
      context: ./backend/user_management_microservice
    container_name: user_management_microservice
    env_file:
      - ./backend/user_management_microservice/.env
    depends_on:
      - mysql
    restart: always
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - backend-net

  restaurant_service:
    build: ./Restaurant/Restaurant
    container_name: restaurant_service
    expose: 
      - "5006"
    restart: always
    networks: 
      - backend-net

  article_service:
    build: ./Restaurant/Article 
    container_name: article_service
    expose:
      - "5007:5007"
    volumes:
      - "/c/Users/Administrator/Documents/Intership and Attachments/CESI Exchange/Study/Elective Software Development/CESI_Eats - Copy/public/images:/app/public/images"

    restart: always
    networks:
      - backend-net 

  delivery_service:
    build: ./Restaurant/delivery-microservice
    container_name: delivery_service
    env_file:
      - ./Restaurant/delivery-microservice/.env
    expose:
      - "5008"
    restart: always
    depends_on:
      - order_service
    networks:
      - backend-net  

  order_service:
    build: ./Restaurant/order_microservice
    container_name: order_service
    env_file:
      - ./Restaurant/order_microservice/.env
    expose:
      - "5009"
    restart: always
    depends_on:
      - article_service
    networks:
      - backend-net  
    
  payment_service:
    build: ./Restaurant/payment_microservice
    container_name: payment_service
    env_file:
      - ./Restaurant/payment_microservice/.env
    expose:
      - "5010:5010"
    restart: always
    depends_on:
      - order_service
    networks:
      - backend-net  
  

  ##frontend
  frontend:
    build: ./Restaurant/my-app/my-app
    container_name: frontend
    expose:
      - "80"
    restart: always
    networks:
      - backend-net


  mysql:
    image: mysql:8.0
    container_name: user-management-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb-test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-net

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - user_service
      - restaurant_service
      - article_service
      - delivery_service
      - order_service
      - payment_service
      - frontend
    networks:
      - backend-net


volumes:
  mysql-data:

networks:
  backend-net:
    driver: bridge