events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        server_name localhost;

        root /usr/share/nginx/html;

        location /authenticate {
            if ($request_method = OPTIONS){
                return 204;
            }

            internal;

            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header x-original-URI $request_uri;

            # proxy_pass http://auth-service:3000/authenticate;
        }

        # location /login {
        #     proxy_pass http://auth-service:3000/login;
        # }
        # location /register {
        #     proxy_pass http://auth-service:3000/register;
        # }
        location /frontend {
            proxy_pass http://frontend-service:3000/;
        }

        location /restaurant {
            proxy_pass http://restaurant-service:3000/;
        }
        location /food {
            proxy_pass http://order-service:3000/;
        }

    }
}