server{
    listen 80;

    ##user management apis
    location /api/users/ {
        proxy_pass http://user_service:5000/api/users/;
    }
    location /api/auth/ {
        proxy_pass http://user_service:5000/api/auth/;
    }

    #restaurant api
    location /restaurants/ {
        proxy_pass http://restaurant_service:5006/restaurants/;
    }
    ##article apis
    location /articles/ {
        proxy_pass http://article_service:5007/articles/;
    }

    ##delivery apis
    location /api/deliveries/ {
        proxy_pass http://delivery_service:5008/api/deliveries/;
    }

    ##order apis
    location /api/orders/ {
        proxy_pass http://order_service:5009/api/orders/;
    }
    location /api/cart/ {
        proxy_pass http://order_service:5009/api/cart/;
    }

    #payment apis
    location api/payments/ {
        proxy_pass http://payment_service:5010/api/payments;
    }

    #frontend
    location / {
        proxy_pass http://frontend:80/;
    }

}